### There are 2 techniques to handle imbalaced datasets:
### 1. Up - Sampling the minority class
### 2. Down - sampling the majority class

In [1]:
import numpy as np
import pandas as pd

np.random.seed(0)

n_samples = 1000
class_0_ratio = 0.9

nclass_0 = int(n_samples * class_0_ratio)
nclass_1 = n_samples - nclass_0

In [2]:
### Creating Dataframe with imbalaced dataset

class_0 = pd.DataFrame({
    'feature 1' : np.random.normal(loc = 0, scale = 1, size = nclass_0),
    'feature 2' : np.random.normal(loc = 0, scale = 1, size = nclass_0),
    'target' : [0] * nclass_0
})

class_1 = pd.DataFrame({
    'feature 1' : np.random.normal(loc = 2, scale = 1, size = nclass_1),
    'feature 2' : np.random.normal(loc = 2, scale = 1, size = nclass_1),
    'target' : [1] * nclass_1
})

df = pd.concat([class_0, class_1]).reset_index(drop = True)

In [3]:
df.head()

   feature 1  feature 2  target
0   1.764052  -1.461733       0
1   0.400157  -0.683440       0
2   0.978738   0.367545       0
3   2.240893   0.190312       0
4   1.867558  -0.851729       0

In [4]:
df.tail()

     feature 1  feature 2  target
995   1.744529   2.097751       1
996   3.685792   3.401523       1
997   0.351954   2.158434       1
998   2.298714   0.858099       1
999   2.910646   0.689030       1

In [5]:
df.shape

(1000, 3)

In [7]:
### Up - sampling the minority class

from sklearn.utils import resample
df_minority = df[df['target'] == 1]
df_majority = df[df['target'] == 0]

df_minority.shape
df_majority.shape

(900, 3)

In [8]:
df_minority_upsampled = resample(df_minority, replace = True, n_samples = len(df_majority), random_state = 42)

df_upsampled = pd.concat([df_majority, df_minority_upsampled]).reset_index(drop = True)

In [ ]:
df_upsampled.shape  ## 900 - 1's, 900 - 0's

(1800, 3)

In [11]:
### Down - Sampling the majority class

df_majority_downsampled = resample(df_majority, replace = False, n_samples = len(df_minority), random_state = 42)

df_downsampled = pd.concat([df_majority_downsampled, df_minority]).reset_index(drop = True)

In [ ]:
df_downsampled.shape    ## 200 - 1's, 200 - 0's

(200, 3)